[package]
name = "loxidize"
version = "0.1.0"
edition = "2021"

[dependencies]
num_enum = "0.7.3"
clap = "4.5.15"
logos = "0.14.1"
rstest = "0.22.0"

[features]
default = ["vm-trace-execution"]
vm-trace-execution = []
